site_name: 此山中
site_author: Zhang Yahuah
copyright: Copyright &copy; 2025 | Zhang Yahuah
nav:
  - 首页: index.md
  - 闲谈: 
    - chat1: chat1.md
    - chat2: chat2.md
  - 笔记: 
    - note1: note1.md
    - note2: note2.md
  - 关于: about.md

theme:
  name: material
  font: false
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: 关闭自动模式
    #primary: blue grey
    - media: "(prefers-color-scheme: light)"
      scheme: default # 日间模式
      primary: indigo # 上方的
      accent: blue # 链接等可交互元件的高亮色
      # teal
      toggle:
        icon: material/brightness-7 # 图标
        name: 切换至夜间模式 # 鼠标悬浮提示
    - media: "(prefers-color-scheme: dark)"
      scheme: slate # 夜间模式
      primary: black
      accent: indigo
      # teal
      toggle:
        icon: material/brightness-4
        name: 切换至日间模式
  features:
    - navigation.top # 返回顶部的按钮 在上滑时出现
    - search.suggest # 搜索输入一些字母时推荐补全整个单词
    - search.highlight # 搜索出的文章关键词加入高亮

markdown_extensions:  #推荐配置Markdown基本语法及其扩展
  - abbr #缩写或名词
  - pymdownx.snippets  #片段，将任意文件或部分内容嵌入到文档中  
  - admonition  #警告或标注
  - pymdownx.details  #细节折叠
  - attr_list   #属性列表（按钮-颜色图标）
  - def_list   #定义列表
  - footnotes  #行内脚注
  - meta   #元数据
  - md_in_html  #HTML 中的 Markdown
  - toc:  #目录
      toc_depth: 3 #目录深度，默认6，0则隐藏
#      title: On this page  #默认值，自动获取
#      permalink: true   #每个标题的末尾添加段落符号锚链接，默认false
#      permalink: ⚓︎  #每个标题的末尾添加自定义符号锚链接
#      permalink_title: Anchor link to this section for reference #在悬停时显示并由屏幕阅读器阅读的锚链接的标题
  - tables #表格（未推荐）
  - pymdownx.arithmatex:  #数学公式
      generic: true  
  - pymdownx.betterem:   #粗体斜体
      smart_enable: all
  - pymdownx.caret
  - pymdownx.betterem
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.smartsymbols
  - pymdownx.tilde
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format:
            !!python/name:pymdownx.superfences.fence_code_format # 代码块高亮插件
  - pymdownx.highlight: # 代码块高亮
      anchor_linenums: true
      linenums: true # 显示行号
     # auto_title: true # 显示编程语言名称
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
extra_css:
  - stylesheets/customize.css # 搜索圆角优化
