site_name: My Docs
theme:
  name: material
  copyright: Copyright &copy; 2024 | Cat Tom
markdown_extensions:  #推荐配置Markdown基本语法及其扩展
  - abbr #缩写或名词
  - pymdownx.snippets  #片段，将任意文件或部分内容嵌入到文档中  
  - admonition  #警告或标注
  - pymdownx.details  #细节折叠
  - attr_list   #属性列表（按钮-颜色图标）
  - def_list   #定义列表
  - footnotes  #行内脚注
  - meta   #元数据
  - md_in_html  #HTML 中的 Markdown
  - toc:  #目录
      toc_depth: 3 #目录深度，默认6，0则隐藏
#      title: On this page  #默认值，自动获取
#      permalink: true   #每个标题的末尾添加段落符号锚链接，默认false
#      permalink: ⚓︎  #每个标题的末尾添加自定义符号锚链接
#      permalink_title: Anchor link to this section for reference #在悬停时显示并由屏幕阅读器阅读的锚链接的标题
  - tables #表格（未推荐）
  - pymdownx.arithmatex:  #数学公式
      generic: true  
  - pymdownx.betterem:   #粗体斜体
      smart_enable: all
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js